<?xml version='1.0'?>

<robot name="my_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:property name="chassis_width" value="0.2" />
  <xacro:property name="chassis_length" value="0.45" />
  <xacro:property name="chassis_height" value="0.02" />

  <xacro:property name="wheel_length" value="0.045" />
  <xacro:property name="wheel_separation" value="0.32" />
  <xacro:property name="wheel_y_offset" value="${(chassis_width + wheel_length + 0.005)/2}" />

  <xacro:property name="camera_width" value="0.02" />
  <xacro:property name="camera_length" value="0.02" />
  <xacro:property name="camera_height" value="0.02" />
  <xacro:property name="camera_mass" value="0.02" />

  <xacro:macro name="wheel" params="fb lr translateX translateY">
    <link name="${fb}_${lr}_wheel">
      <visual>
        <origin xyz="0 0 0" rpy=" 0 1.5707 1.5707"/>
        <geometry>
          <cylinder radius="0.1" length="0.05" />
        </geometry>
      </visual>

      <collision>
        <origin xyz="0 0 0" rpy=" 0 1.5707 1.5707"/>
        <geometry>
          <cylinder radius="0.1" length="0.05" />
        </geometry>
      </collision>

      <inertial>
        <mass value="5"/>
        <origin xyz="0.0 0 0" rpy=" 0 1.5707 1.5707"/>
        <inertia
            ixx="0.1" ixy="0" ixz="0"
            iyy="0.1" iyz="0"
            izz="0.1"
        />
      </inertial>    
    </link>

    <joint type="continuous" name="${fb}_${lr}_hinge">
      <origin xyz="${translateX} ${translateY} 0" rpy="0 0 0"/>
      <child link="${fb}_${lr}_wheel"/>
      <parent link="chassis"/>
      <axis xyz="0 1 0" rpy="0 0 0"/>
      <limit effort="100" velocity="100"/>
      <dynamics damping="1.0" friction="1.0"/>
    </joint>
  </xacro:macro>

  <link name="robot_footprint"></link>

  <joint name="robot_footprint_joint" type="fixed">
    <origin xyz="0 0 0" rpy="0 0 0" />
    <parent link="robot_footprint"/>
    <child link="chassis" />
  </joint>

  <link name='chassis'>
    <pose>0 0 0.1 0 0 0</pose>

    <inertial>
      <mass value="15.0"/>
      <origin xyz="0.0 0 0" rpy=" 0 0 0"/>
      <inertia
          ixx="0.1" ixy="0" ixz="0"
          iyy="0.1" iyz="0"
          izz="0.1"
      />
    </inertial>

    <collision name='collision'>
      <origin xyz="0 0 0" rpy=" 0 0 0"/> 
      <geometry>
        <box size=".4 .2 .1"/>
      </geometry>
    </collision>

    <visual name='chassis_visual'>
      <origin xyz="0 0 0" rpy=" 0 0 0"/>
      <geometry>
        <box size=".4 .2 .1"/>
      </geometry>
    </visual>

    <!-- <collision name='back_caster_collision'>
      <origin xyz="-0.15 0 -0.05" rpy=" 0 0 0"/>
      <geometry>
        <sphere radius="0.0499"/>
      </geometry>
    </collision>

    <visual name='back_caster_visual'>
      <origin xyz="-0.15 0 -0.05" rpy=" 0 0 0"/>
      <geometry>
        <sphere radius="0.05"/>
      </geometry>
    </visual> -->

  </link>

  <xacro:wheel fb="front" lr="right" translateX="${wheel_separation/2}" translateY="-${wheel_y_offset}" />
  <xacro:wheel fb="front" lr="left" translateX="${wheel_separation/2}" translateY="${wheel_y_offset}" />

  <xacro:wheel fb="back" lr="right" translateX="-${wheel_separation/2}" translateY="-${wheel_y_offset}" />
  <xacro:wheel fb="back" lr="left" translateX="-${wheel_separation/2}" translateY="${wheel_y_offset}" />

  <!-- camera -->
  <link name="camera">
    <inertial>
      <mass value="${camera_mass}"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6"/>
    </inertial>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${camera_length} ${camera_width} ${camera_height}"/>
      </geometry>
    </collision>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${camera_length} ${camera_width} ${camera_height}"/>
      </geometry>
    </visual>
  </link>

  <joint type="fixed" name="camera_joint">
    <origin xyz="${chassis_length/2 - camera_length} 0 ${chassis_height/2 + camera_height/2}" rpy="0 0 0"/>
    <child link="camera"/>
    <parent link="chassis"/>
    <axis xyz="0 1 0" rpy="0 0 0"/>
  </joint>

  <!-- lidar -->
  <link name="hokuyo">
    <inertial>
      <mass value="1e-5"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6"/>
    </inertial>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size=".1 .1 .1"/>
      </geometry>
    </collision>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://my_robot/meshes/hokuyo.dae"/>
      </geometry>
    </visual>
  </link>

  <joint type="fixed" name="hokuyo_joint">
    <origin xyz="0 0 .02" rpy="0 0 0"/>
    <child link="hokuyo"/>
    <parent link="chassis"/>
    <axis xyz="0 1 0" rpy="0 0 0"/>
  </joint>
</robot>
